name: 签到

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 30 1 * * ?
  watch:
    types: started
    
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: 签到
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
        - name: Checkout codes
          uses: actions/checkout@v2
 
        - name: Run 号码1
          env:
           haoma: ${{ secrets.HAOMA }}
           mm: ${{ secrets.MM }}
           appid: ${{ secrets.APPID }}
          run: |
           bash CnUnicom.sh ${haoma} ${mm} ${appid}
           
        - name: Run 号码2
          env:
           haoma: ${{ secrets.HAOMA2 }}
           mm: ${{ secrets.MM }}
           appid: ${{ secrets.APPID }}
          run: |
           bash CnUnicom.sh ${haoma} ${mm} ${appid}

        
